"""
gen_lenet_mnist.py
Train LeNet-300-100 (classic published MLP, LeCun et al. 1998) on MNIST to its
published ~98% test accuracy, then export FP32 weights (transposed to the
accelerator's out-major GEMV layout [M][N]), biases, a few pre-normalized test
images, their labels, and reference predictions to a C header.

Run:  conda run -n CD2 python example_model/gen_lenet_mnist.py
Output: example_model/lenet_mnist_data.h
"""
import numpy as np, struct, os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf

tf.random.set_seed(1); np.random.seed(1)   # reproducible

# ---- MNIST (built into keras; ~11MB auto-download, no external dataset) -------
(xtr, ytr), (xte, yte) = tf.keras.datasets.mnist.load_data()
xtr = (xtr.astype(np.float32) / 255.0).reshape(-1, 784)   # normalize to [0,1]
xte = (xte.astype(np.float32) / 255.0).reshape(-1, 784)

# ---- LeNet-300-100 : 784 -> 300 -> 100 -> 10 (ReLU; logits out, no softmax) --
model = tf.keras.Sequential([
    tf.keras.layers.Input((784,)),
    tf.keras.layers.Dense(300, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(10),
])
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
model.fit(xtr, ytr, epochs=12, batch_size=128, validation_split=0.1, verbose=2)
_, acc = model.evaluate(xte, yte, verbose=0)
print(f"\n=== Full MNIST test accuracy: {acc*100:.2f}% ===")

# ---- Weights: Keras kernel is [in,out]; accel wants [out][in] -> transpose ----
W1, b1 = model.layers[0].get_weights()   # W1:(784,300)
W2, b2 = model.layers[1].get_weights()   # (300,100)
W3, b3 = model.layers[2].get_weights()   # (100,10)
W1o, W2o, W3o = W1.T, W2.T, W3.T          # -> [M][N], row m = output m's weights

# ---- K test images + reference predictions -----------------------------------
K = 10
xt, yt = xte[:K], yte[:K].astype(np.int32)
ref_pred = np.argmax(model.predict(xt, verbose=0), axis=1).astype(np.int32)
print("labels   :", yt.tolist())
print("ref preds:", ref_pred.tolist())

# ---- Emit C header -----------------------------------------------------------
def f2h(f): return '0x{:08X}'.format(struct.unpack('<I', struct.pack('<f', float(f)))[0])
def emit_f(name, arr):
    flat = np.asarray(arr, np.float32).flatten()
    s = [f'static const unsigned int {name}[{len(flat)}] = {{']
    for i in range(0, len(flat), 8):
        s.append('  ' + ', '.join(f2h(v) for v in flat[i:i+8]) + ',')
    s.append('};'); return '\n'.join(s)
def emit_i(name, arr):
    flat = np.asarray(arr, np.int32).flatten()
    s = [f'static const int {name}[{len(flat)}] = {{']
    s.append('  ' + ', '.join(str(int(v)) for v in flat) + ',')
    s.append('};'); return '\n'.join(s)

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'lenet_mnist_data.h')
with open(out, 'w') as f:
    f.write('/* LeNet-300-100 on MNIST, FP32. Auto-generated by gen_lenet_mnist.py */\n')
    f.write(f'/* Full-test accuracy: {acc*100:.2f}%.  Weights are out-major [M][N]. */\n')
    f.write('#ifndef LENET_MNIST_DATA_H\n#define LENET_MNIST_DATA_H\n\n')
    f.write('#define L1_N 784\n#define L1_M 300\n')
    f.write('#define L2_N 300\n#define L2_M 100\n')
    f.write('#define L3_N 100\n#define L3_M 10\n')
    f.write(f'#define N_TEST {K}\n\n')
    f.write(emit_f('fc1_w', W1o) + '\n\n'); f.write(emit_f('fc1_b', b1) + '\n\n')
    f.write(emit_f('fc2_w', W2o) + '\n\n'); f.write(emit_f('fc2_b', b2) + '\n\n')
    f.write(emit_f('fc3_w', W3o) + '\n\n'); f.write(emit_f('fc3_b', b3) + '\n\n')
    f.write(emit_f('test_images', xt) + '\n\n')
    f.write(emit_i('test_labels', yt) + '\n\n')
    f.write(emit_i('ref_pred', ref_pred) + '\n\n')
    f.write('#endif /* LENET_MNIST_DATA_H */\n')
print(f"\nWritten: {out}  ({os.path.getsize(out)/1e6:.1f} MB text)")
