"""
gen_encoder_test.py
Extract StarDist 2D_versatile_fluo first encoder block (two conv layers)
and compute expected output for a 6x6 input patch.
Outputs firmware/encoder_test_data.h.

Run with: conda run -n CD2 python firmware/gen_encoder_test.py
"""

import numpy as np
import struct
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

from stardist.models import StarDist2D

# ---- Load model and extract first two conv layers ----------------------------
model = StarDist2D.from_pretrained('2D_versatile_fluo')

# Find the first two conv layers (first encoder block)
conv_layers = [l for l in model.keras_model.layers if 'conv2d' in l.name]
conv1 = conv_layers[0]  # 3x3x1->32
conv2 = conv_layers[1]  # 3x3x32->32

W1, b1 = conv1.get_weights()   # W1: (3,3,1,32)  b1: (32,)
W2, b2 = conv2.get_weights()   # W2: (3,3,32,32) b2: (32,)

print(f"Conv1: kernel={W1.shape}, bias={b1.shape}, padding={conv1.padding}, activation={conv1.activation.__name__}")
print(f"Conv2: kernel={W2.shape}, bias={b2.shape}, padding={conv2.padding}, activation={conv2.activation.__name__}")

# ---- Generate deterministic 6x6 float32 input --------------------------------
inp_flat = np.linspace(0.0, 1.0, 36, dtype=np.float32)
inp = inp_flat.reshape(6, 6)

OUT_H, OUT_W = 6, 6
N_CH1 = 32  # Conv1 output channels
N_CH2 = 32  # Conv2 output channels

# ---- Conv1: im2col with same padding (pad=1) ---------------------------------
inp_padded = np.pad(inp, 1, mode='constant', constant_values=0.0).astype(np.float32)  # (8, 8)

conv1_raw = np.zeros((OUT_H, OUT_W, N_CH1), dtype=np.float32)
for oi in range(OUT_H):
    for oj in range(OUT_W):
        patch = inp_padded[oi:oi+3, oj:oj+3].flatten()  # (9,)
        for c in range(N_CH1):
            w_c = W1[:, :, 0, c].flatten()  # (9,)
            s = np.float32(0.0)
            for k in range(9):
                s = np.float32(s + np.float32(patch[k]) * np.float32(w_c[k]))
            conv1_raw[oi, oj, c] = np.float32(s + np.float32(b1[c]))

# Apply ReLU (StarDist uses relu after each conv)
conv1_relu = np.maximum(conv1_raw, np.float32(0.0)).astype(np.float32)
print(f"\nConv1 output range (after relu): [{conv1_relu.min():.4f}, {conv1_relu.max():.4f}]")
print(f"Conv1 zeros (from relu): {np.sum(conv1_relu == 0)} / {conv1_relu.size}")

# ---- Conv2: im2col on conv1_relu, same padding (pad=1) -----------------------
# Pad conv1_relu: (6,6,32) -> (8,8,32)
conv1_padded = np.pad(conv1_relu, ((1,1),(1,1),(0,0)), mode='constant', constant_values=0.0).astype(np.float32)

conv2_raw = np.zeros((OUT_H, OUT_W, N_CH2), dtype=np.float32)
for oi in range(OUT_H):
    for oj in range(OUT_W):
        # im2col patch: 3x3x32 = 288 values
        patch = conv1_padded[oi:oi+3, oj:oj+3, :].flatten()  # (288,)
        for c in range(N_CH2):
            w_c = W2[:, :, :, c].flatten()  # (288,)
            s = np.float32(0.0)
            for k in range(288):
                s = np.float32(s + np.float32(patch[k]) * np.float32(w_c[k]))
            conv2_raw[oi, oj, c] = np.float32(s + np.float32(b2[c]))

conv2_relu = np.maximum(conv2_raw, np.float32(0.0)).astype(np.float32)
print(f"Conv2 output range (after relu): [{conv2_relu.min():.4f}, {conv2_relu.max():.4f}]")
print(f"Conv2 zeros (from relu): {np.sum(conv2_relu == 0)} / {conv2_relu.size}")

# ---- Verify against Keras end-to-end -----------------------------------------
import tensorflow as tf
inp_keras = inp.reshape(1, 6, 6, 1).astype(np.float32)
out1_keras = conv1(inp_keras).numpy()[0]  # (6,6,32) with relu
out2_keras = conv2(tf.constant(out1_keras.reshape(1,6,6,32))).numpy()[0]  # (6,6,32) with relu

# Compare conv1
diff1 = np.abs(conv1_relu - out1_keras)
print(f"\nConv1 max diff vs Keras: {diff1.max():.2e}")

# Compare conv2
diff2 = np.abs(conv2_relu - out2_keras)
print(f"Conv2 max diff vs Keras: {diff2.max():.2e}")

# ---- Helper functions ---------------------------------------------------------
def float_to_hex(f):
    return '0x{:08X}'.format(struct.unpack('<I', struct.pack('<f', float(f)))[0])

def arr_to_c(name, arr, comment=''):
    flat = arr.flatten()
    lines = []
    if comment:
        lines.append(f'/* {comment} */')
    lines.append(f'#define {name.upper()}_LEN {len(flat)}')
    lines.append(f'static const unsigned int {name}[{len(flat)}] = {{')
    for i in range(0, len(flat), 4):
        chunk = flat[i:i+4]
        lines.append('    ' + ', '.join(float_to_hex(v) for v in chunk) + ',')
    lines.append('};')
    return '\n'.join(lines)

# ---- Write C header -----------------------------------------------------------
out_path = os.path.join(os.path.dirname(__file__), 'encoder_test_data.h')

with open(out_path, 'w') as f:
    f.write('/* Auto-generated by gen_encoder_test.py -- do not edit manually */\n')
    f.write('/* StarDist 2D_versatile_fluo, first encoder block (two 3x3 conv layers) */\n')
    f.write('/* Input: 6x6 ramp 0..1; same padding; ReLU between layers */\n\n')
    f.write('#ifndef ENCODER_TEST_DATA_H\n#define ENCODER_TEST_DATA_H\n\n')

    f.write('#define ENC_OUT_H 6\n')
    f.write('#define ENC_OUT_W 6\n')
    f.write('#define ENC_CH1   32  /* Conv1 output channels */\n')
    f.write('#define ENC_CH2   32  /* Conv2 output channels */\n')
    f.write('#define ENC_K1    9   /* Conv1 kernel spatial size: 3x3x1 */\n')
    f.write('#define ENC_K2    288 /* Conv2 kernel spatial size: 3x3x32 */\n\n')

    # Padded input (8x8)
    f.write(arr_to_c('enc_input_padded', inp_padded,
                     'Padded input: 8x8 float32 (1-pixel zero pad around 6x6 ramp)'))
    f.write('\n\n')

    # Conv1 weights: [channel][spatial] = [32][9]
    W1_out = np.stack([W1[:,:,0,c].flatten() for c in range(N_CH1)])
    f.write(arr_to_c('enc_conv1_weights', W1_out,
                     'Conv1 weights: [out_ch * 9 + k], 32 channels x 9 spatial'))
    f.write('\n\n')

    f.write(arr_to_c('enc_conv1_biases', b1, 'Conv1 biases: 32 values'))
    f.write('\n\n')

    # Conv1 expected output (after ReLU), flattened [oi][oj][c]
    f.write(arr_to_c('enc_conv1_expected', conv1_relu,
                     'Conv1 output (after ReLU): shape (6,6,32) = 1152 values'))
    f.write('\n\n')

    # Conv2 weights: [out_ch][spatial] = [32][288]
    # W2 shape is (3,3,32,32) — flatten spatial dims for each output channel
    W2_out = np.stack([W2[:,:,:,c].flatten() for c in range(N_CH2)])
    f.write(arr_to_c('enc_conv2_weights', W2_out,
                     'Conv2 weights: [out_ch * 288 + k], 32 channels x 288 spatial'))
    f.write('\n\n')

    f.write(arr_to_c('enc_conv2_biases', b2, 'Conv2 biases: 32 values'))
    f.write('\n\n')

    # Conv2 expected output (after ReLU), flattened [oi][oj][c]
    f.write(arr_to_c('enc_conv2_expected', conv2_relu,
                     'Conv2 output (after ReLU): shape (6,6,32) = 1152 values'))
    f.write('\n\n')

    # Conv1 output (after ReLU) padded to 8x8x32 for Conv2 im2col
    # Firmware needs this to gather patches; store as flat array [i][j][c]
    f.write(arr_to_c('enc_conv1_padded', conv1_padded,
                     'Conv1 output padded: 8x8x32 = 2048 values (for Conv2 im2col)'))
    f.write('\n\n')

    f.write('#endif /* ENCODER_TEST_DATA_H */\n')

print(f"\nWritten: {out_path}")
print(f"  enc_input_padded: 64 values")
print(f"  enc_conv1_weights: {W1_out.size} values")
print(f"  enc_conv1_biases: {b1.size} values")
print(f"  enc_conv1_expected: {conv1_relu.size} values")
print(f"  enc_conv2_weights: {W2_out.size} values")
print(f"  enc_conv2_biases: {b2.size} values")
print(f"  enc_conv2_expected: {conv2_relu.size} values")
print(f"  enc_conv1_padded: {conv1_padded.size} values")
